genome: /homes/nsvandervegt/data-processing-snakemake/data/genome.fa
samples:
  A: /homes/nsvandervegt/data-processing-snakemake/data/samples/A.fastq
  B: /homes/nsvandervegt/data-processing-snakemake/data/samples/B.fastq
  C: /homes/nsvandervegt/data-processing-snakemake/data/samples/C.fastq