"""
Diagnostic Genome Analysis - Snakemake Pipeline

Preperation:
    -Retrieving remote genome (code provided, but currently offline)
	-BWA Index

Pipeline tools:
	-FastQC
	-Trimmomatic
	-BWA MEM Mapping
	-Samtools Sort
	-Markduplicates
	-MpileUp
	-VarScan 2
	-Annovar
"""

configfile: "config.yaml"
#include: "rules/preperation/get_remote_genome.snakefile"
include: "rules/preperation/bwa_index.snakefile"
include: "rules/fastqc.snakefile"
include: "rules/trimmomatic.snakefile"
include: "rules/bwa_mem.snakefile"
include: "rules/samtools_sort.snakefile"
include: "rules/markduplicates.snakefile"
include: "rules/mpileup.snakefile"
include: "rules/varscan.snakefile"
include: "rules/annovar.snakefile"

# PIPELINE RULES.
rule report:
	input:
		expand("fastqc/{sample}_fastqc.html", sample=config["samples"]),
		expand("annovar/{sample}.hg19_multianno.txt", sample=config["samples"])
