"""
Diagnostic Genome Analysis - Snakemake Pipeline

Preperation rules:
    -Retrieving remote genome (code provided, but currently offline)
    -Retrieving remote Annovar databases
	-BWA Index

Tools supported:
	-FastQC
	-Trimmomatic
	-BWA MEM Mapping
	-Samtools sort
	-Markduplicates
	-Bamtools split
	-MpileUp
	-VarScan 2
	-Annovar
"""

configfile: "config.yaml"

#include: "rules/preperation/get_remote_genome.snakefile"
include: "rules/preperation/get_remote_annovar_dbs.snakefile"
include: "rules/preperation/bwa_index.snakefile"
include: "rules/fastqc.snakefile"
include: "rules/trimmomatic.snakefile"
include: "rules/bwa_mem.snakefile"
include: "rules/samtools_sort.snakefile"
include: "rules/bamtools_split.snakefile"
include: "rules/marked_duplicates.snakefile"
include: "rules/mpileup.snakefile"
include: "rules/varscan.snakefile"
include: "rules/concat_vcf.snakefile"
include: "rules/annovar.snakefile"


# PIPELINE RULES.
rule report:
	input:
		expand("runs/{sample}/results/{sample}_{num}_fastqc.html",
			sample=config["samples"],
			num=["R1", "R2"]),
		expand("runs/{sample}/results/{sample}.{genome_build}_multianno.txt",
			sample=config["samples"],
			genome_build = config["genome_build"])
	log:
		notebook = "runs/run_results_notebook.ipynb"
	notebook:
		"notebooks/diagnostic_genome_analysis.ipynb"


